org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true

# Gradle plugins
#dependencyManagementVersion=1.0.11.RELEASE
dependencyCheckVersion=7.1.0.1
sonarQubeVersion=4.0.0.2929
#springBootVersion=2.5.13

# Build
version=1.0.0
artifactoryContextUrl=https://artifactory.tools.verimi.cloud/artifactory


# Verimi dependencies
identityOwnerServiceVersion=1018872-8594a511-RELEASE
adminApiServiceVersion=1331903-2668ac6d-RELEASE
importExportServiceVersion=865118-89efedae-RELEASE
masterDataServiceVersion=869277-cd1ae024-RELEASE
securityServiceVersion=868167-f65a5d3a-RELEASE
paymentDataClientVersion=1.0.0-SNAPSHOT

# Libraries
apachePoiVersion=3.17
gsonVersion=2.8.2
httpClientVersion=5.3
jacksonAnnotationsVersion=2.17.1
jacksonCoreVersion=2.17.1
jacksonDatabindVersion=2.17.1
javaFakerVersion=1.0.2
jodatimeVersion=2.9.9
jsonVersion=20090211
log4jVersion=2.8.2
logbackVersion=1.5.6
lombokVersion=1.18.24
postgresqlVersion=42.7.3
pdfBoxVersion=2.0.30
seleniumVersion=4.41.0
slf4jVersion=2.0.13
snakeYamlVersion=2.2
testNgVersion=6.11
appiumJavaVersion=10.0.0
fixtureFactoryVersion=3.1.0
microsoftGraphVersion=5.80.0
microsoftGraphCoreVersion=2.0.21
azureIdentityVersion=1.12.1
assertjCoreVersion=3.24.2
webdriverManagerVersion=5.8.0
gatlingVersion=3.11.2
gatlingGradlePluginVersion=3.9.2.1
restAssuredVersion=5.4.0
bouncycastleVersion=1.77
zapVersion=2.15.0
zapClientApiVersion=1.14.0
libphonenumberVersion=8.13.11

